
namespace Mangos.Common.Enums.Gossip
{
    public enum Gossip_Guard_Spell
    {
        GOSSIP_GUARD_SPELL_WARRIOR = 64,
        GOSSIP_GUARD_SPELL_PALADIN = 65,
        GOSSIP_GUARD_SPELL_HUNTER = 66,
        GOSSIP_GUARD_SPELL_ROGUE = 67,
        GOSSIP_GUARD_SPELL_PRIEST = 68,
        GOSSIP_GUARD_SPELL_UNKNOWN1 = 69,
        GOSSIP_GUARD_SPELL_SHAMAN = 70,
        GOSSIP_GUARD_SPELL_MAGE = 71,
        GOSSIP_GUARD_SPELL_WARLOCK = 72,
        GOSSIP_GUARD_SPELL_UNKNOWN2 = 73,
        GOSSIP_GUARD_SPELL_DRUID = 74
    }
}