
namespace Mangos.Common.Enums.Gossip
{
    public enum Gossip_Guard_Skill
    {
        GOSSIP_GUARD_SKILL_ALCHEMY = 80,
        GOSSIP_GUARD_SKILL_BLACKSMITH = 81,
        GOSSIP_GUARD_SKILL_COOKING = 82,
        GOSSIP_GUARD_SKILL_ENCHANT = 83,
        GOSSIP_GUARD_SKILL_FIRSTAID = 84,
        GOSSIP_GUARD_SKILL_FISHING = 85,
        GOSSIP_GUARD_SKILL_HERBALISM = 86,
        GOSSIP_GUARD_SKILL_LEATHER = 87,
        GOSSIP_GUARD_SKILL_MINING = 88,
        GOSSIP_GUARD_SKILL_SKINNING = 89,
        GOSSIP_GUARD_SKILL_TAILORING = 90,
        GOSSIP_GUARD_SKILL_ENGINERING = 91
    }
}