--
-- Table structure for table `npc_text`
--

DROP TABLE IF EXISTS `npc_text`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `npc_text` (
  `ID` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'The unique identifier of the text entry.',
  `text0_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text0_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang0` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text ingame.',
  `prob0` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em0_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em0_0` smallint(5) DEFAULT NULL COMMENT 'Emote to play when text is displayed.',
  `em0_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em0_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em0_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em0_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed',
  `text1_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text1_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang1` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob1` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em1_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em1_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em1_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em1_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em1_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em1_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text2_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text2_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang2` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob2` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em2_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em2_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em2_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em2_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em2_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em2_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text3_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text3_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang3` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob3` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em3_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em3_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em3_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em3_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em3_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em3_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text4_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text4_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang4` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob4` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em4_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em4_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em4_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em4_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em4_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em4_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text5_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text5_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang5` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob5` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em5_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em5_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em5_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em5_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em5_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em5_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text6_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text6_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang6` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob6` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em6_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em6_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em6_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em6_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em6_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em6_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  `text7_0` longtext COMMENT 'This is the locale text that is displayed if the creature is male.',
  `text7_1` longtext COMMENT 'This is the locale text that is displayed if the creature is female.',
  `lang7` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The language of the text in game.',
  `prob7` float NOT NULL DEFAULT '0' COMMENT 'This is the probability that the creature will say this text.',
  `em7_0_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait before the first emote is played.',
  `em7_0` smallint(5) DEFAULT NULL COMMENT 'emote to play when text is displayed.',
  `em7_1_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the first emote are played, before the second emote.',
  `em7_1` smallint(5) DEFAULT NULL COMMENT 'Second emote to play when text is displayed.',
  `em7_2_delay` smallint(5) DEFAULT NULL COMMENT 'Time to wait after the second emote are played, before the third emote.',
  `em7_2` smallint(5) DEFAULT NULL COMMENT 'Third emote to play when text is displayed.',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `db_version` VALUES (21, 02, 000, "npc_text_prep", "npc_text_prep");