
namespace Mangos.Common.Enums.Spell
{
    public enum SpellAuraStates : int
    {
        AURASTATE_FLAG_DODGE_BLOCK = 1,
        AURASTATE_FLAG_HEALTH20 = 2,
        AURASTATE_FLAG_BERSERK = 4,
        AURASTATE_FLAG_JUDGEMENT = 16,
        AURASTATE_FLAG_PARRY = 64,
        AURASTATE_FLAG_LASTKILLWITHHONOR = 512,
        AURASTATE_FLAG_CRITICAL = 1024,
        AURASTATE_FLAG_HEALTH35 = 4096,
        AURASTATE_FLAG_IMMOLATE = 8192,
        AURASTATE_FLAG_REJUVENATE = 16384,
        AURASTATE_FLAG_POISON = 32768
    }
}