
namespace Mangos.Common.Enums.Spell
{
    public enum SpellSchoolMask : int
    {
        SPELL_SCHOOL_MASK_NONE = 0x0,
        SPELL_SCHOOL_MASK_NORMAL = 0x1,
        SPELL_SCHOOL_MASK_HOLY = 0x2,
        SPELL_SCHOOL_MASK_FIRE = 0x4,
        SPELL_SCHOOL_MASK_NATURE = 0x8,
        SPELL_SCHOOL_MASK_FROST = 0x10,
        SPELL_SCHOOL_MASK_SHADOW = 0x20,
        SPELL_SCHOOL_MASK_ARCANE = 0x40,
        SPELL_SCHOOL_MASK_SPELL = SPELL_SCHOOL_MASK_FIRE | SPELL_SCHOOL_MASK_NATURE | SPELL_SCHOOL_MASK_FROST | SPELL_SCHOOL_MASK_SHADOW | SPELL_SCHOOL_MASK_ARCANE,
        SPELL_SCHOOL_MASK_MAGIC = SPELL_SCHOOL_MASK_HOLY | SPELL_SCHOOL_MASK_SPELL,
        SPELL_SCHOOL_MASK_ALL = SPELL_SCHOOL_MASK_NORMAL | SPELL_SCHOOL_MASK_MAGIC
    }
}