--
-- Table structure for table `item_template`
--

DROP TABLE IF EXISTS `item_template`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `item_template` (
  `entry` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Item prototype ID.',
  `class` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Class of the item.',
  `subclass` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The subclass of the item template.',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT 'Item name.',
  `displayid` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'A display model identifier for the Item.',
  `Quality` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Quality of item.',
  `Flags` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Item prototype flags.',
  `BuyCount` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT 'Stack size by vendors.',
  `BuyPrice` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Item buying price (coppers).',
  `SellPrice` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Item selling price (coppers).',
  `InventoryType` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Inventory type.',
  `AllowableClass` mediumint(9) NOT NULL DEFAULT '-1' COMMENT 'Mask of allowed classes.',
  `AllowableRace` mediumint(9) NOT NULL DEFAULT '-1' COMMENT 'Mask of allowed races.',
  `ItemLevel` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Level of item.',
  `RequiredLevel` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Required level.',
  `RequiredSkill` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Required skill type.',
  `RequiredSkillRank` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Required skill value.',
  `requiredspell` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Required spell (See Spell.dbc).',
  `requiredhonorrank` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Required honor rank.',
  `RequiredCityRank` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'DEPRECATED: the city rank required. City ranks did not make it into WoW.',
  `RequiredReputationFaction` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Required faction for reputation check (See Faction.dbc).',
  `RequiredReputationRank` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Required minimal reputation rank.',
  `maxcount` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'The maximum amount of copies of the item that a character may have.',
  `stackable` smallint(5) unsigned NOT NULL DEFAULT '1' COMMENT 'Maximum stack size.',
  `ContainerSlots` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Defines the amount of slots for items of type container or ammunition container.',
  `stat_type1` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value1` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type2` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value2` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type3` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value3` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type4` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value4` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type5` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value5` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type6` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value6` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type7` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value7` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type8` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value8` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type9` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value9` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `stat_type10` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'An item modifier to apply for this item. ',
  `stat_value10` smallint(6) NOT NULL DEFAULT '0' COMMENT 'The value to add for the matching modifier.',
  `dmg_min1` float NOT NULL DEFAULT '0' COMMENT 'The minimum damage caused by the item.',
  `dmg_max1` float NOT NULL DEFAULT '0' COMMENT 'The maximum damage caused by the item.',
  `dmg_type1` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of damage the matching dmg_min/dmg_max fields cause.',
  `dmg_min2` float NOT NULL DEFAULT '0' COMMENT 'The minimum damage caused by the item.',
  `dmg_max2` float NOT NULL DEFAULT '0' COMMENT 'The maximum damage caused by the item.',
  `dmg_type2` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of damage the matching dmg_min/dmg_max fields cause.',
  `dmg_min3` float NOT NULL DEFAULT '0' COMMENT 'The minimum damage caused by the item.',
  `dmg_max3` float NOT NULL DEFAULT '0' COMMENT 'The maximum damage caused by the item.',
  `dmg_type3` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of damage the matching dmg_min/dmg_max fields cause.',
  `dmg_min4` float NOT NULL DEFAULT '0' COMMENT 'The minimum damage caused by the item.',
  `dmg_max4` float NOT NULL DEFAULT '0' COMMENT 'The maximum damage caused by the item.',
  `dmg_type4` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of damage the matching dmg_min/dmg_max fields cause.',
  `dmg_min5` float NOT NULL DEFAULT '0' COMMENT 'The minimum damage caused by the item.',
  `dmg_max5` float NOT NULL DEFAULT '0' COMMENT 'The maximum damage caused by the item.',
  `dmg_type5` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of damage the matching dmg_min/dmg_max fields cause.',
  `armor` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'The armor value of the item.',
  `holy_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Holy resistance.',
  `fire_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Fire resistance.',
  `nature_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Nature resistance.',
  `frost_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Frost resistance.',
  `shadow_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Shadow resistance.',
  `arcane_res` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Arcane resistance.',
  `delay` smallint(5) unsigned NOT NULL DEFAULT '1000' COMMENT 'The delay in milliseconds between successive hits for the item.',
  `ammo_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of ammunition the item uses. Arrows = 2; Bullets = 3',
  `RangedModRange` float NOT NULL DEFAULT '0',
  `spellid_1` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item can cast or trigger a spell, this is the reference.',
  `spelltrigger_1` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of trigger for the matching spellid entry.',
  `spellcharges_1` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'The amount of charges for the spell referenced in the matching spellid entry. ',
  `spellppmRate_1` float NOT NULL DEFAULT '0' COMMENT 'This controls the proc per minute rate for a spell.',
  `spellcooldown_1` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell.',
  `spellcategory_1` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'A spell category identifier.',
  `spellcategorycooldown_1` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell category.',
  `spellid_2` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item can cast or trigger a spell, this is the references.',
  `spelltrigger_2` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of trigger for the matching spellid entry.',
  `spellcharges_2` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'The amount of charges for the spell referenced in the matching spellid entry. ',
  `spellppmRate_2` float NOT NULL DEFAULT '0' COMMENT 'This controls the proc per minute rate for a spell.',
  `spellcooldown_2` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell.',
  `spellcategory_2` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'A spell category identifier.',
  `spellcategorycooldown_2` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell category.',
  `spellid_3` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item can cast or trigger a spell, this is the references.',
  `spelltrigger_3` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of trigger for the matching spellid entry.',
  `spellcharges_3` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'The amount of charges for the spell referenced in the matching spellid entry. ',
  `spellppmRate_3` float NOT NULL DEFAULT '0' COMMENT 'This controls the proc per minute rate for a spell.',
  `spellcooldown_3` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell.',
  `spellcategory_3` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'A spell category identifier.',
  `spellcategorycooldown_3` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell category.',
  `spellid_4` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item can cast or trigger a spell, this is the references.',
  `spelltrigger_4` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of trigger for the matching spellid entry.',
  `spellcharges_4` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'The amount of charges for the spell referenced in the matching spellid entry. ',
  `spellppmRate_4` float NOT NULL DEFAULT '0' COMMENT 'This controls the proc per minute rate for a spell.',
  `spellcooldown_4` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell.',
  `spellcategory_4` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'A spell category identifier.',
  `spellcategorycooldown_4` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell category.',
  `spellid_5` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item can cast or trigger a spell, this is the references.',
  `spelltrigger_5` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The type of trigger for the matching spellid entry.',
  `spellcharges_5` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'The amount of charges for the spell referenced in the matching spellid entry. ',
  `spellppmRate_5` float NOT NULL DEFAULT '0' COMMENT 'This controls the proc per minute rate for a spell.',
  `spellcooldown_5` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell.',
  `spellcategory_5` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'A spell category identifier.',
  `spellcategorycooldown_5` int(11) NOT NULL DEFAULT '-1' COMMENT 'The cooldown in milliseconds for the matching spell category.',
  `bonding` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Defines if and how and item will be bound to a character. ',
  `description` varchar(255) NOT NULL DEFAULT '' COMMENT 'A short - usually one sentence - description of the item. Mostly flavor texts.',
  `PageText` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If the item should be readable, e.g. for letters.',
  `LanguageID` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The material to be used as background for items with page texts set.',
  `PageMaterial` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The material to be used as background for items with page texts set.',
  `startquest` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Quest ID (See quest_template.entry).',
  `lockid` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Lock ID (See Lock.dbc).',
  `Material` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Material type.',
  `sheath` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'The value of this field controls how characters will show or hide items worn, e.',
  `RandomProperty` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Random property type (See item_enchantment_template.entry).',
  `block` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If an item is a shield, this field holds the block chance.',
  `itemset` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If an item is part of an item set, this references the item set''s identifier.',
  `MaxDurability` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'The maximum durability for an item.',
  `area` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'If an item is only usable on a specific map, this is the reference.',
  `Map` smallint(6) NOT NULL DEFAULT '0' COMMENT 'If an item is only usable on a specific map, this is the reference.',
  `BagFamily` mediumint(9) NOT NULL DEFAULT '0' COMMENT 'If an item is a bag, this holds a bit-mask corresponding to bag families to whic',
  `DisenchantID` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Disenchant template (See disenchant_loot_template.entry).',
  `FoodType` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'If an item is usable as pet food, this table is the reference.',
  `minMoneyLoot` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'This field specifies the minimum amount in a container holding money.',
  `maxMoneyLoot` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'This field specifies the maximum amount in a container holding money.',
  `Duration` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Items may have a duration set until the get removed from a character''s inventory',
  `ExtraFlags` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'With these flags it is possible to set rare conditions on an item. ',
  PRIMARY KEY (`entry`),
  KEY `items_index` (`class`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='Item System';
/*!40101 SET character_set_client = @saved_cs_client */;

