
namespace Mangos.Common.Enums.Global
{
    public enum ActivateTaxiReplies : byte
    {
        ERR_TAXIOK = 0,
        ERR_TAXIUNSPECIFIEDSERVERERROR = 1,
        ERR_TAXINOSUCHPATH = 2,
        ERR_TAXINOTENOUGHMONEY = 3,
        ERR_TAXITOOFARAWAY = 4,
        ERR_TAXINOVENDORNEARBY = 5,
        ERR_TAXINOTVISITED = 6,
        ERR_TAXIPLAYERBUSY = 7,
        ERR_TAXIPLAYERALREADYMOUNTED = 8,
        ERR_TAXIPLAYERSHAPESHIFTED = 9,
        ERR_TAXIPLAYERMOVING = 10,
        ERR_TAXISAMENODE = 11,
        ERR_TAXINOTSTANDING = 12
    }
}