
namespace Mangos.Common.Enums.Global
{
    public enum SHEATHE_TYPE : byte
    {
        SHEATHETYPE_NONE = 0,
        SHEATHETYPE_MAINHAND = 1,
        SHEATHETYPE_OFFHAND = 2,
        SHEATHETYPE_LARGEWEAPONLEFT = 3,
        SHEATHETYPE_LARGEWEAPONRIGHT = 4,
        SHEATHETYPE_HIPWEAPONLEFT = 5,
        SHEATHETYPE_HIPWEAPONRIGHT = 6,
        SHEATHETYPE_SHIELD = 7
    }
}