
namespace Mangos.Common.Enums.Global
{
    public enum TradeSkill : int
    {
        TRADESKILL_ALCHEMY = 1,
        TRADESKILL_BLACKSMITHING = 2,
        TRADESKILL_COOKING = 3,
        TRADESKILL_ENCHANTING = 4,
        TRADESKILL_ENGINEERING = 5,
        TRADESKILL_FIRSTAID = 6,
        TRADESKILL_HERBALISM = 7,
        TRADESKILL_LEATHERWORKING = 8,
        TRADESKILL_POISONS = 9,
        TRADESKILL_TAILORING = 10,
        TRADESKILL_MINING = 11,
        TRADESKILL_FISHING = 12,
        TRADESKILL_SKINNING = 13
    }
}